name: 'Publish test coverage'
description: 'Send test coverage to sqs for consumption'

inputs:
  AWS_ACCOUNT:
    required: true
  AWS_API_REGION:
    required: true
  DOMAIN:
    required: true
  FUNCTIONS_COVERAGE_PCT:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT }}:role/github-actions
        role-session-name: github-actions-oidc-session
        aws-region: ${{ inputs.AWS_API_REGION }}
    - uses: isbang/sqs-action@v0.1.1
      with:
        sqs-url: https://sqs.eu-west-1.amazonaws.com/${{inputs.AWS_ACCOUNT}}/env-code-coverage-Queue
        message: '{"project":"${{ inputs.DOMAIN }}", "score":"${{ inputs.FUNCTIONS_COVERAGE_PCT }}"}'