name: 'Deploy'
description: 'Deploy...'

inputs:
  DOMAIN:
    required: true
  OWNER:
    required: true
  TEAM:
    required: true
  AWS_ACCOUNT:
    required: true
  AWS_DEPLOY_REGION:
    required: true
  AWS_API_REGION:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT }}:role/github-actions
        role-session-name: github-actions-oidc-session
        aws-region: ${{ inputs.AWS_API_REGION }}
    - name: Deploy
      shell: bash
      run: |
        sam build
        sam deploy \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --stack-name ${{ github.event.repository.name }} \
        --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
        --region ${{ inputs.AWS_DEPLOY_REGION  }} \
        --s3-prefix ${{ github.event.repository.name }} \
        --resolve-s3 \
        --config-file ./github/actions/deploy/deploy-config.toml \
        --tags \
          'domain=${{ inputs.DOMAIN }} \
          owner=${{ inputs.OWNER }} \
          team=${{ inputs.TEAM }}'
