name: Deploy to AWS

on:
  workflow_call:
    inputs:
      AWS_DEPLOY_REGION:
        required: false
        type: string
        default: 'eu-west-1'
      branch:
        required: true
        type: string
      domain:
        required: true
        type: string
      owner:
        required: true
        type: string
      team:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_API:
        required: true
      AWS_REGION:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: run-tests
        name: Run tests
        uses: ./.github/actions/test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/report.json
      - id: publish-results
        name: Publish test results
        uses: ./.github/actions/test-coverage-sqs
        with:
          DOMAIN: ${{ needs.Setup.outputs.domain }}
          AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
          AWS_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
          FUNCTIONS_COVERAGE_PCT: ${{ steps.run-tests.outputs.functions-coverage }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo configuration
        run: |
          echo "Config below"
          echo "-----------------------------------------"
          echo "Branch:           ${{ needs.Setup.outputs.branch }}"
          echo "Domain:           ${{ needs.Setup.outputs.domain }}"
          echo "Owner:            ${{ needs.Setup.outputs.owner }}"
          echo "Team:             ${{ needs.Setup.outputs.team }}"
          echo "-----------------------------------------"
          echo "Team domain:      ${{ needs.Account.outputs.domain }}"
          echo "AWS account:      ${{ needs.Account.outputs.account }}"
          echo "AWS region:       ${{ inputs.AWS_DEPLOY_REGION }}"
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          DOMAIN: ${{ needs.Setup.outputs.domain }}
          OWNER: ${{ needs.Setup.outputs.owner }}
          TEAM: ${{ needs.Setup.outputs.team }}
          AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
          AWS_DEPLOY_REGION: ${{ inputs.AWS_DEPLOY_REGION }}
          AWS_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
