name: Deploy to AWS

on:
  workflow_call:
    inputs:
      AWS_DEPLOY_REGION:
        required: false
        type: string
        default: 'eu-west-1'
      domain:
        required: true
        type: string
      team:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: true
      AWS_CICD_ACCOUNT:
        required: true
      AWS_CICD_API_URL:
        required: true
      AWS_CICD_API_REGION:
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  Account:
    uses: mathem-se/gh-account-mapping/.github/workflows/workflow.yml@main
    with:
      branch: ${{ github.ref_name }}
      role-session-name: 'github-actions-oidc-session'
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_CICD_ACCOUNT }}
      AWS_API: ${{ secrets.AWS_CICD_API_URL }}
      AWS_REGION: ${{ secrets.AWS_CICD_API_REGION }}

  Test:
    needs: [Account]
    uses: mathem-se/ecom-gh-actions/.github/workflows/nested/test-deploy.yml@upgrade
    with:
      domain: ${{ inputs.domain }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
      AWS_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}

    inputs:
      domain:
        required: true
      team:
        required: true
      environment:
        required: true
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_API_REGION:
        required: true
      AWS_CICD_API_REGION:
        required: true
      NODE_AUTH_TOKEN:
        required: true


Deploy:
    needs: [Account, Test]
    uses: mathem-se/ecom-gh-actions/.github/workflows/nested/release-aws.yml@upgrade
    with:
      domain: ${{ inputs.domain }}
      team: ${{ inputs.domain }}
      environment: ${{ needs.Account.outputs.environment }}
      AWS_DEPLOY_REGION: ${{ inputs.AWS_DEPLOY_REGION }}
    secrets:
      AWS_CICD_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
      NODE_AUTH_TOKEN: secrets.NODE_AUTH_TOKEN
      AWS_ACCOUNT: ${{ needs.Account.outputs.account }}

  Deploy:
    needs: [Account, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ needs.Account.outputs.account }}:role/github-actions
          role-session-name: github-actions-oidc-session
          aws-region: ${{ secrets.AWS_API_REGION }}
      - name: Build
        shell: bash
        run: |
          sam build \
          --parallel \
          --config-file ./samconfig.toml \
          --config-env ${{ inputs.environment }}
      - name: Deploy
        shell: bash
        run: |
          sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name ${{ github.event.repository.name }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --region ${{ secrets.AWS_CICD_API_REGION }} \
          --s3-prefix ${{ github.event.repository.name }} \
          --resolve-s3 \
          --config-file ./samconfig.toml \
          --config-env ${{ inputs.environment }} \
          --tags \
            'domain=${{ inputs.domain }} \
            team=${{ inputs.team }}'
