name: Test PR
on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run test
        run: |
          npm ci
          npm run test:ci
        shell: bash
      - name: Download develop test report
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ github.token}}
          workflow: deploy.yml
          workflow_conclusion: success
          branch: develop
          name: code-coverage-report
          path: ./coverage/main
      - name: Create test report
        continue-on-error: true
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/main/report.json
          annotations: failed-tests
