name: Setup

on:
  workflow_call:
    outputs:
      domain:
        description: 'repo domain'
        value: ${{ jobs.Setup.outputs.domain }}
      team:
        description: 'repo team'
        value: ${{ jobs.Setup.outputs.team }}
      owner:
        description: 'repo owner'
        value: ${{ jobs.Setup.outputs.owner }}

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.tags.outputs.domain }}
      team: ${{ steps.tags.outputs.team }}
      owner: ${{ steps.tags.outputs.owner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: tags-test
        name: Set tags for test
        if: github.ref_name == 'develop'
        run: |
          echo "domain=$(cat ./parameters.test.json | jq -r .Tags.domain)" >> $GITHUB_ENV
          echo "team=$(cat ./parameters.test.json | jq -r .Tags.team)" >> $GITHUB_ENV
          echo "owner=$(cat ./parameters.test.json | jq -r .Tags.owner)" >> $GITHUB_ENV
      - id: tags-prod
        name: Set tags for prod
        if: |
          github.ref_name == 'main' ||
          github.ref_name == 'master'
        run: |
          echo "domain=$(cat ./parameters.prod.json | jq -r .Tags.domain)" >> $GITHUB_ENV
          echo "team=$(cat ./parameters.prod.json | jq -r .Tags.team)" >> $GITHUB_ENV
          echo "owner=$(cat ./parameters.prod.json | jq -r .Tags.owner)" >> $GITHUB_ENV
      - id: tags
        name: Set tags
        run: |
          echo "::set-output name=domain::${{ env.domain }}"
          echo "::set-output name=team::${{ env.team }}"
          echo "::set-output name=owner::${{ env.owner }}"
