name: Test and publish results

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_API_REGION:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: run-tests
        name: Run tests
        uses: ./.github/actions/test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/report.json
      - id: publish-results
        name: Publish test results
        uses: ./.github/actions/test-coverage-sqs
        with:
          DOMAIN: ${{ inputs.domain }}
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
          AWS_API_REGION: ${{ secrets.AWS_API_REGION }}
          FUNCTIONS_COVERAGE_PCT: ${{ steps.run-tests.outputs.functions-coverage }}
