name: Test and publish results

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT:
        required: true
      AWS_API_REGION:
        required: true
    outputs:
      functions-coverage:
        description: 'Unit test functions coverage'
        value: ${{ jobs.Test.extract-coverage-pct.outputs.result}}

permissions:
  id-token: write
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Test
        run: |
          npm ci
          npm run compile
          npm run test:ci-coverage
        shell: bash
      - uses: actions/github-script@v6
        id: extract-coverage-pct
        with:
          result-encoding: string
          script: |
            const coverageSummary = require("./coverage/coverage-summary.json")
            return coverageSummary.total.functions.pct
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./coverage/report.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/github-actions
          role-session-name: github-actions-oidc-session
          aws-region: ${{ secrets.AWS_API_REGION }}
      - uses: isbang/sqs-action@v0.1.1
        if: |
          github.ref_name == 'develop' ||
          github.ref_name == 'main' ||
          github.ref_name == 'master'
        with:
          sqs-url: https://sqs.eu-west-1.amazonaws.com/${{secrets.AWS_ACCOUNT}}/env-code-coverage-Queue
          message: '{"project":"${{ inputs.domain }}", "score":"${{ steps.extract-coverage-pct.outputs.result }}"}'
